name: splashify
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.1+2

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  auto_route: ^4.2.1
  cached_network_image: ^3.2.1
  carousel_slider: ^4.1.1
  cupertino_icons: ^1.0.5
  equatable: ^2.0.3
  firebase_auth: ^3.6.0
  firebase_core: ^1.20.0
  firebase_crashlytics: ^2.8.6
  firebase_messaging: ^12.0.1
  firebase_storage: ^10.3.3
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1
  flutter_local_notifications: ^9.8.0+1
  flutter_screen_wake: ^1.0.2
  freezed_annotation: ^2.1.0
  fzregex: ^2.0.0
  get_it: ^7.2.0
  google_fonts: ^3.0.1
  http: ^0.13.4
  injectable: ^1.5.3
  json_annotation: ^4.6.0
  shared_preferences: ^2.0.15
  url_launcher: ^6.1.5

dev_dependencies:
  auto_route_generator: ^4.2.0
  build_runner: ^2.2.0
  change_app_package_name: ^1.1.0
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter
  freezed: ^2.1.0+1
  injectable_generator: ^1.5.4
  json_serializable: ^6.3.1

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter.
flutter:
  uses-material-design: true
  assets:
    - assets/images/
